# parameters
base:
  project_name: delivery-time-estimation
  target: Time_taken(min)

load_dataset:
  bucket: delivery-time-estimate-data
  filename: train.csv
  raw_data: /data/raw

make_dataset:
  input_path: data/raw/train.csv
  test_split: 0.2
  seed: 42
  export_path: data/interim

feature_engineering:
  input_path__train: data/interim/train.csv
  input_path__test: data/interim/test.csv
  export_path: data/processed
  labels_: src/features/labels.txt
  filename_train: processed_train 
  filename_test: processed_test
